### ISSUE TITLE
Add ubuntu-based packer images for compute queue buildkite stack

### ISSUE THREAD

**Issue by jhedev** [grid-x/images#12]
* Move packer setup from our elastic-ci-stack fork to this repo
* Create two templates, one for docker + aufs and one for docker + overlay2
* Check if any changes have been made upstream and integrate

**Comment by jhedev** [comment]
@tobjaw if there are any questions feel free to ask.

**Comment by tobjaw** [comment]
Ok, so I think the images themselves should be fine (see PR #14 for the current state), but testing them turned out to be rather problematic.  

Testing them during image provisioning seemed like a good idea, but now I'm not so sure if this is the way to go.
In order to test vital functions of the images (e.g. whether `docker` is running, if the `buildkite-agent` is online, ...), the image has to be initialised, which happens on the [AWS Agent launch](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/buildkite-elastic.yml#L491). Specifically, it runs the script [bk-install-elastic-stack](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/bin/bk-install-elastic-stack.sh), which we - as it is - cannot run during image provisioning.  
Now, I guess it would be possible to do some init during image provisioning and remove it from the `bk-install-elastic-stack` script, but this will probably make integrating upstream changes more difficult in the future.
  
As an alternative, we could test in CI - e.g. spin up an actual EC2 stack and run some e2e tests against that, [similar to upstream](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/.buildkite/pipeline.yml).  
Then again, this repo contains only the image, so I'm not sure how much work it is to get the whole stack up and running 🤷‍♂️ 

Curious to hear your thoughts on this, @jhedev

**Comment by jhedev** [comment]
First of all: nice work and as always you very thoroughly analysed the problem. Thanks :) 👍 

> In order to test vital functions of the images (e.g. whether docker is running, if the buildkite-agent is online, ...), the image has to be initialised, which happens on the AWS Agent launch. Specifically, it runs the script bk-install-elastic-stack, which we - as it is - cannot run during image provisioning. Now, I guess it would be possible to do some init during image provisioning and remove it from the bk-install-elastic-stack script, but this will probably make integrating upstream changes more difficult in the future.

I agree that it doesn't make sense to move the initialization to the image provisioning etc. However, I guess we could still test if the requirements for the buildkite agent, e.g. docker, are running. As far as I see there is nothing important in the bk-install-elastic-stack script that prevents docker from being able to start without it. 

But IMHO we don't need to add more tests right now because the initial goal was to extract the template form the forked project.

> As an alternative, we could test in CI - e.g. spin up an actual EC2 stack and run some e2e tests against that, similar to upstream.
Then again, this repo contains only the image, so I'm not sure how much work it is to get the whole stack up and running 🤷‍♂️

Let's keep it simple for now and don't do this. If we see need for better e2e testing in the future we can still do it.

**Comment by tobjaw** [comment]
Thanks for the detailed answer.  
I focused so much on getting the tests to run that I didn't stop to take a look if we actually need all of that. 😄 
I've added basic docker tests (check if running, check if correct file system); PR #14 is ready to review.

**Comment by jhedev** [comment]
yeah saw it already. Good work. I think that's enough for now :)

**Comment by tobjaw** [comment]
closed with #14
